from django.db import models
from django.contrib.auth.models import User

class TechPack(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name ='techpacks')

    name = models.CharField(max_length=200)

    created_at = models.DateTimeField(auto_now_add=True)

    updated_at = models.DateTimeField(auto_now=True)

    #ai details
    is_ai_generated = models.BooleanField(default=False, help_text="Indicates if this tech pack was generated by AI.")
    prompt = models.TextField(blank=True, help_text="AI generation prompt used for this tech pack.")

    #JSON store for tech pack details
    json_data = models.JSONField(default=dict)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Tech Pack'
        verbose_name_plural = 'Tech Packs'

    def __str__(self):
        return f"{self.name} - {self.user.username}" 
