# Generated by Django 5.2.8 on 2026-01-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpack_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techpack',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tech Pack', 'verbose_name_plural': 'Tech Packs'},
        ),
        migrations.AddField(
            model_name='techpack',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Indicates if this tech pack was generated by AI.'),
        ),
        migrations.AlterField(
            model_name='techpack',
            name='prompt',
            field=models.TextField(blank=True, help_text='AI generation prompt used for this tech pack.'),
        ),
        migrations.AlterField(
            model_name='techpack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
